Fixing all these scary validation errors in one move!
```
Error: ERROR IN CONFIG FILE:
[#/jobs] 16 schema violations found
Any string key is allowed as job name.
1. [#/jobs/commands] 0 subschemas matched instead of one
|   1. [#/jobs/commands] only 0 subschema matches out of 2
|   |   1. [#/jobs/commands] no subschema matched out of the total 2 subschemas
|   |   |   1. [#/jobs/commands] 0 subschemas matched instead of one
|   |   |   |   1. [#/jobs/commands] required key [docker] not found
|   |   |   |   2. [#/jobs/commands] required key [machine] not found
|   |   |   |   3. [#/jobs/commands] required key [macos] not found
|   |   |   2. [#/jobs/commands] required key [executor] not found
|   |   |   |   A job must have one of `docker`, `machine`, `macos` or `executor` (which can provide docker/machine/macos information).
|   |   2. [#/jobs/commands] 3 schema violations found
|   |   |   1. [#/jobs/commands] extraneous key [install_command] is not permitted
|   |   |   |   Permitted keys:
|   |   |   |     - description
|   |   |   |     - parallelism
|   |   |   |     - macos
|   |   |   |     - resource_class
|   |   |   |     - docker
|   |   |   |     - steps
|   |   |   |     - working_directory
|   |   |   |     - machine
|   |   |   |     - environment
|   |   |   |     - executor
|   |   |   |     - shell
|   |   |   |     - parameters
|   |   |   |   Passed keys:
|   |   |   |     - install_command
|   |   |   |     - my_inline_command
|   |   |   2. [#/jobs/commands] extraneous key [my_inline_command] is not permitted
|   |   |   |   Permitted keys:
|   |   |   |     - description
|   |   |   |     - parallelism
|   |   |   |     - macos
|   |   |   |     - resource_class
|   |   |   |     - docker
|   |   |   |     - steps
|   |   |   |     - working_directory
|   |   |   |     - machine
|   |   |   |     - environment
|   |   |   |     - executor
|   |   |   |     - shell
|   |   |   |     - parameters
|   |   |   |   Passed keys:
|   |   |   |     - install_command
|   |   |   |     - my_inline_command
|   |   |   3. [#/jobs/commands] required key [steps] not found
|   2. [#/jobs/commands] expected type: String, found: Mapping
|   |   Job may be a string reference to another job
2. [#/jobs/executors] 0 subschemas matched instead of one
|   1. [#/jobs/executors] only 0 subschema matches out of 2
|   |   1. [#/jobs/executors] no subschema matched out of the total 2 subschemas
|   |   |   1. [#/jobs/executors] 0 subschemas matched instead of one
|   |   |   |   1. [#/jobs/executors] required key [docker] not found
|   |   |   |   2. [#/jobs/executors] required key [machine] not found
|   |   |   |   3. [#/jobs/executors] required key [macos] not found
|   |   |   2. [#/jobs/executors] required key [executor] not found
|   |   |   |   A job must have one of `docker`, `machine`, `macos` or `executor` (which can provide docker/machine/macos information).
|   |   2. [#/jobs/executors] 3 schema violations found
|   |   |   1. [#/jobs/executors] extraneous key [default] is not permitted
|   |   |   |   Permitted keys:
|   |   |   |     - description
|   |   |   |     - parallelism
|   |   |   |     - macos
|   |   |   |     - resource_class
|   |   |   |     - docker
|   |   |   |     - steps
|   |   |   |     - working_directory
|   |   |   |     - machine
|   |   |   |     - environment
|   |   |   |     - executor
|   |   |   |     - shell
|   |   |   |     - parameters
|   |   |   |   Passed keys:
|   |   |   |     - my_inline_executor
|   |   |   |     - default
|   |   |   2. [#/jobs/executors] extraneous key [my_inline_executor] is not permitted
|   |   |   |   Permitted keys:
|   |   |   |     - description
|   |   |   |     - parallelism
|   |   |   |     - macos
|   |   |   |     - resource_class
|   |   |   |     - docker
|   |   |   |     - steps
|   |   |   |     - working_directory
|   |   |   |     - machine
|   |   |   |     - environment
|   |   |   |     - executor
|   |   |   |     - shell
|   |   |   |     - parameters
|   |   |   |   Passed keys:
|   |   |   |     - my_inline_executor
|   |   |   |     - default
|   |   |   3. [#/jobs/executors] required key [steps] not found
|   2. [#/jobs/executors] expected type: String, found: Mapping
|   |   Job may be a string reference to another job
```